declare module '*.module.css'
declare module '*.module.less'
declare module '*.jpg'
declare module '*.png'
declare module '*.gif'
declare module '*.pdf'
declare module '*.doc'
declare module 'react-helmet'
